## Open config file and metadata

This example shows how to handle and parse metadata and configuration files using paidiverpy package

## Import dependencies

In [10]:
%load_ext autoreload
%autoreload 2
from paidiverpy import Paidiverpy
from paidiverpy.config import Configuration
from paidiverpy.metadata_parser import MetadataParser
from paidiverpy.open_layer import OpenLayer

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Loading metadata and configuration files

There are several ways to load and parse the metadata and the configuration file:

- Option 1: using the Paidiverpy class
- Option 2: using other processing classes, like OpenLayer#
- Option 3: using Configuration class and MetadataParser class

### Option 1: Using Paidiverpy class

In [11]:
# Instantiate the class
# You may need to change the parameters on the config_simple.yml file for the correct paths on your computer
paidiverpy = Paidiverpy(config_file_path="../config_files/config_simple.yml")

In [12]:
# See the type of config
type(paidiverpy.config)

paidiverpy.config.configuration.Configuration

In [13]:
# Print config as json
paidiverpy.config

{
    "general": {
        "name": "raw",
        "step_name": "open",
        "sample_data": "benthic_csv",
        "input_path": "/home/tobfer/.paidiverpy_cache/benthic_csv/images",
        "output_path": "output",
        "metadata_path": "/home/tobfer/.paidiverpy_cache/benthic_csv/metadata/metadata_benthic_csv.csv",
        "metadata_type": "CSV_FILE",
        "image_open_args": "PNG",
        "append_data_to_metadata": "/home/tobfer/.paidiverpy_cache/benthic_csv/metadata/appended_metadata_benthic_csv.csv",
        "n_jobs": 1,
        "track_changes": true,
        "rename": "datetime",
        "sampling": [
            {
                "name": "sampling",
                "step_name": "sampling",
                "test": false,
                "params": {
                    "value": 0.1,
                    "raise_error": false
                },
                "mode": "percent"
            }
        ],
        "convert": [
            {
                "name": "convert",
                "step_name": "convert",
                "test": false,
                "params": {
                    "output_bits": 8,
                    "raise_error": false
                },
                "mode": "bits"
            },
            {
                "name": "convert",
                "step_name": "convert",
                "test": false,
                "params": {
                    "to": "gray",
                    "channel_selector": 0,
                    "raise_error": false
                },
                "mode": "to"
            }
        ]
    },
    "steps": []
}

In [14]:
# See metadata information
paidiverpy.get_metadata()

,ID,image-filename,XResolution,YResolution,ExposureTime,FNumber,ISO,image-datetime,MaxApertureValue,WhiteBalance,...,speed_of_sound_m_s,temperature_c,positioning_ok,attitude_ok,depth_ok,altitude_ok,X,phototime,flag,point
0,430.0,20180611041421.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:21,2.828427,FLASH,...,1545.388,1.5059,1,1,1,1,NaN,2018-06-11 04:14:21,0,POINT (-153.60531587 11.25172554)
1,431.0,20180611041431.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:31,2.828427,FLASH,...,1545.447,1.5236,1,1,1,1,NaN,2018-06-11 04:14:31,0,POINT (-153.60531372 11.25171832)
2,432.0,20180611041441.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:41,2.828427,FLASH,...,1545.452,1.5234,1,1,1,1,NaN,2018-06-11 04:14:41,0,POINT (-153.60531259 11.2517135)
3,433.0,20180611041451.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:51,2.828427,FLASH,...,1545.363,1.4911,1,1,1,1,NaN,2018-06-11 04:14:51,0,POINT (-153.60531313 11.25170837)
4,434.0,20180611041501.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:01,2.828427,FLASH,...,1545.324,1.4747,1,1,1,1,NaN,2018-06-11 04:15:01,0,POINT (-153.60531414 11.25170299)
5,435.0,20180611041511.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:11,2.828427,FLASH,...,1545.298,1.4635,1,1,1,1,NaN,2018-06-11 04:15:11,0,POINT (-153.60531664 11.25169768)
6,436.0,20180611041521.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:21,2.828427,FLASH,...,1545.315,1.4697,1,1,1,1,NaN,2018-06-11 04:15:21,0,POINT (-153.6053176 11.25169125)
7,437.0,20180611041531.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:31,2.828427,FLASH,...,1545.326,1.4727,1,1,1,1,NaN,2018-06-11 04:15:31,0,POINT (-153.60532046 11.25168357)
8,438.0,20180611041541.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:41,2.828427,FLASH,...,1545.266,1.4532,1,1,1,1,NaN,2018-06-11 04:15:41,0,POINT (-153.60532129 11.25167559)
9,439.0,20180611041551.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:51,2.828427,FLASH,...,1545.263,1.4512,1,1,1,1,NaN,2018-06-11 04:15:51,0,POINT (-153.60532147 11.25166737)
10,440.0,20180611041601.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:01,2.828427,FLASH,...,1545.248,1.4490,1,1,1,1,NaN,2018-06-11 04:16:01,0,POINT (-153.60532189 11.25165983)
11,441.0,20180611041611.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:11,2.828427,FLASH,...,1545.249,1.4485,1,1,1,1,NaN,2018-06-11 04:16:11,0,POINT (-153.60532254 11.25165416)
12,442.0,20180611041621.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:21,2.828427,FLASH,...,1545.232,1.4455,1,1,1,1,NaN,2018-06-11 04:16:21,0,POINT (-153.60532147 11.25164913)
13,443.0,20180611041631.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:31,2.828427,FLASH,...,1545.228,1.4456,1,1,1,1,NaN,2018-06-11 04:16:31,0,POINT (-153.60532064 11.2516466)
14,444.0,20180611041641.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:41,2.828427,FLASH,...,1545.241,1.4515,1,1,1,1,NaN,2018-06-11 04:16:41,0,POINT (-153.60532022 11.25164222)
15,445.0,20180611041651.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:51,2.828427,FLASH,...,1545.232,1.4506,1,1,1,1,NaN,2018-06-11 04:16:51,0,POINT (-153.60531968 11.25163773)
16,446.0,20180611041701.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:01,2.828427,FLASH,...,1545.237,1.4540,1,1,1,1,NaN,2018-06-11 04:17:01,0,POINT (-153.60532004 11.25163429)
17,447.0,20180611041711.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:11,2.828427,FLASH,...,1545.247,1.4593,1,1,1,1,NaN,2018-06-11 04:17:11,0,POINT (-153.60532082 11.25163155)
18,448.0,20180611041721.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:21,2.828427,FLASH,...,1545.228,1.4537,1,1,1,1,NaN,2018-06-11 04:17:21,0,POINT (-153.60532022 11.25162976)
19,449.0,20180611041731.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:31,2.828427,FLASH,...,1545.206,1.4478,1,1,1,1,NaN,2018-06-11 04:17:31,0,POINT (-153.60531831 11.25162916)
20,450.0,20180611041741.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:41,2.828427,FLASH,...,1545.206,1.4487,1,1,1,1,NaN,2018-06-11 04:17:41,0,POINT (-153.60531468 11.25162876)
21,451.0,20180611041751.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:51,2.828427,FLASH,...,1545.198,1.4473,1,1,1,1,NaN,2018-06-11 04:17:51,0,POINT (-153.60531062 11.25162821)
22,452.0,20180611041801.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:01,2.828427,FLASH,...,1545.190,1.4460,1,1,1,1,NaN,2018-06-11 04:18:01,0,POINT (-153.60530782 11.25162813)
23,453.0,20180611041811.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:11,2.828427,FLASH,...,1545.203,1.4546,1,1,1,1,NaN,2018-06-11 04:18:11,0,POINT (-153.60529894 11.25163219)
24,454.0,20180611041821.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:21,2.828427,FLASH,...,1545.205,1.4557,1,1,1,1,NaN,2018-06-11 04:18:21,0,POINT (-153.60529078 11.251633)
25,455.0,20180611041831.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:31,2.828427,FLASH,...,1545.222,1.4606,1,1,1,1,NaN,2018-06-11 04:18:31,0,POINT (-153.60528577 11.25163374)
26,456.0,20180611041841.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:41,2.828427,FLASH,...,1545.154,1.4391,1,1,1,1,NaN,2018-06-11 04:18:41,0,POINT (-153.60527719 11.25163777)
27,457.0,20180611041851.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:51,2.828427,FLASH,...,1545.169,1.4447,1,1,1,0,NaN,2018-06-11 04:18:51,0,POINT (-153.60527218 11.25163858)
28,458.0,20180611041901.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:01,2.828427,FLASH,...,1545.159,1.4435,1,1,1,1,NaN,2018-06-11 04:19:01,0,POINT (-153.60526246 11.25164123)
29,459.0,20180611041911.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:11,2.828427,FLASH,...,1545.252,1.4755,1,1,1,1,NaN,2018-06-11 04:19:11,0,POINT (-153.60525466 11.25164016)
30,460.0,20180611041921.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:21,2.828427,FLASH,...,1545.194,1.4549,1,1,1,1,NaN,2018-06-11 04:19:21,0,POINT (-153.60524786 11.25163778)
31,461.0,20180611041931.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:31,2.828427,FLASH,...,1545.182,1.4517,1,1,1,1,NaN,2018-06-11 04:19:31,0,POINT (-153.60524077 11.25163374)
32,462.0,20180611041941.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:41,2.828427,FLASH,...,1545.189,1.4538,1,1,1,1,NaN,2018-06-11 04:19:41,0,POINT (-153.60523183 11.25162942)
33,463.0,20180611041951.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:51,2.828427,FLASH,...,1545.155,1.4427,1,1,1,1,NaN,2018-06-11 04:19:51,0,POINT (-153.60522104 11.25162529)
34,464.0,20180611042001.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:01,2.828427,FLASH,...,1545.132,1.4345,1,1,1,1,NaN,2018-06-11 04:20:01,0,POINT (-153.60521204 11.25162354)
35,465.0,20180611042011.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:11,2.828427,FLASH,...,1545.125,1.4327,1,1,1,1,NaN,2018-06-11 04:20:11,0,POINT (-153.6052031 11.25162276)
36,466.0,20180611042021.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:21,2.828427,FLASH,...,1545.124,1.4325,1,1,1,1,NaN,2018-06-11 04:20:21,0,POINT (-153.60519493 11.25162345)
37,467.0,20180611042031.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:31,2.828427,FLASH,...,1545.121,1.4321,1,1,1,1,NaN,2018-06-11 04:20:31,0,POINT (-153.60518772 11.25162512)
38,468.0,20180611042041.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:41,2.828427,FLASH,...,1545.116,1.4319,1,1,1,1,NaN,2018-06-11 04:20:41,0,POINT (-153.60518069 11.2516276)
39,469.0,20180611042051.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:51,2.828427,FLASH,...,1545.114,1.4314,1,1,1,1,NaN,2018-06-11 04:20:51,0,POINT (-153.60517508 11.2516303)
40,470.0,20180611042101.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:01,2.828427,FLASH,...,1545.111,1.4318,1,1,1,1,NaN,2018-06-11 04:21:01,0,POINT (-153.60516984 11.25163181)
41,471.0,20180611042111.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:11,2.828427,FLASH,...,1545.107,1.4315,1,1,1,1,NaN,2018-06-11 04:21:11,0,POINT (-153.60516435 11.2516341)
42,472.0,20180611042121.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:21,2.828427,FLASH,...,1545.111,1.4350,1,1,1,1,NaN,2018-06-11 04:21:21,0,POINT (-153.6051516 11.25164437)
43,473.0,20180611042131.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:31,2.828427,FLASH,...,1545.106,1.4378,1,1,1,1,NaN,2018-06-11 04:21:31,0,POINT (-153.60514236 11.25164693)
44,474.0,20180611042141.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:41,2.828427,FLASH,...,1545.109,1.4385,1,1,1,1,NaN,2018-06-11 04:21:41,0,POINT (-153.60513384 11.25165041)
45,475.0,20180611042151.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:51,2.828427,FLASH,...,1545.102,1.4329,1,1,1,1,NaN,2018-06-11 04:21:51,0,POINT (-153.60512829 11.25165104)
46,476.0,20180611042201.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:01,2.828427,FLASH,...,1545.102,1.4327,1,1,1,1,NaN,2018-06-11 04:22:01,0,POINT (-153.60512269 11.25165186)
47,477.0,20180611042211.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:11,2.828427,FLASH,...,1545.097,1.4326,1,1,1,1,NaN,2018-06-11 04:22:11,0,POINT (-153.60511554 11.25165272)
48,478.0,20180611042221.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:21,2.828427,FLASH,...,1545.115,1.4382,1,1,1,1,NaN,2018-06-11 04:22:21,0,POINT (-153.60511047 11.25165643)

### Option 2: Using other processing classes, like OpenLayer

In [15]:
open_layer = OpenLayer(config_file_path="../config_files/config_simple.yml")

In [16]:
# Print config as json
open_layer.config

{
    "general": {
        "name": "raw",
        "step_name": "open",
        "sample_data": "benthic_csv",
        "input_path": "/home/tobfer/.paidiverpy_cache/benthic_csv/images",
        "output_path": "output",
        "metadata_path": "/home/tobfer/.paidiverpy_cache/benthic_csv/metadata/metadata_benthic_csv.csv",
        "metadata_type": "CSV_FILE",
        "image_open_args": "PNG",
        "append_data_to_metadata": "/home/tobfer/.paidiverpy_cache/benthic_csv/metadata/appended_metadata_benthic_csv.csv",
        "n_jobs": 1,
        "track_changes": true,
        "rename": "datetime",
        "sampling": [
            {
                "name": "sampling",
                "step_name": "sampling",
                "test": false,
                "params": {
                    "value": 0.1,
                    "raise_error": false
                },
                "mode": "percent"
            }
        ],
        "convert": [
            {
                "name": "convert",
                "step_name": "convert",
                "test": false,
                "params": {
                    "output_bits": 8,
                    "raise_error": false
                },
                "mode": "bits"
            },
            {
                "name": "convert",
                "step_name": "convert",
                "test": false,
                "params": {
                    "to": "gray",
                    "channel_selector": 0,
                    "raise_error": false
                },
                "mode": "to"
            }
        ]
    },
    "steps": []
}

In [17]:
# See metadata information
# The metadata in this case may have more information because the
# openlayer class extracts the exif information from the files
open_layer.get_metadata()

,ID,image-filename,XResolution,YResolution,ExposureTime,FNumber,ISO,image-datetime,MaxApertureValue,WhiteBalance,...,speed_of_sound_m_s,temperature_c,positioning_ok,attitude_ok,depth_ok,altitude_ok,X,phototime,flag,point
0,430.0,20180611041421.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:21,2.828427,FLASH,...,1545.388,1.5059,1,1,1,1,NaN,2018-06-11 04:14:21,0,POINT (-153.60531587 11.25172554)
1,431.0,20180611041431.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:31,2.828427,FLASH,...,1545.447,1.5236,1,1,1,1,NaN,2018-06-11 04:14:31,0,POINT (-153.60531372 11.25171832)
2,432.0,20180611041441.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:41,2.828427,FLASH,...,1545.452,1.5234,1,1,1,1,NaN,2018-06-11 04:14:41,0,POINT (-153.60531259 11.2517135)
3,433.0,20180611041451.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:51,2.828427,FLASH,...,1545.363,1.4911,1,1,1,1,NaN,2018-06-11 04:14:51,0,POINT (-153.60531313 11.25170837)
4,434.0,20180611041501.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:01,2.828427,FLASH,...,1545.324,1.4747,1,1,1,1,NaN,2018-06-11 04:15:01,0,POINT (-153.60531414 11.25170299)
5,435.0,20180611041511.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:11,2.828427,FLASH,...,1545.298,1.4635,1,1,1,1,NaN,2018-06-11 04:15:11,0,POINT (-153.60531664 11.25169768)
6,436.0,20180611041521.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:21,2.828427,FLASH,...,1545.315,1.4697,1,1,1,1,NaN,2018-06-11 04:15:21,0,POINT (-153.6053176 11.25169125)
7,437.0,20180611041531.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:31,2.828427,FLASH,...,1545.326,1.4727,1,1,1,1,NaN,2018-06-11 04:15:31,0,POINT (-153.60532046 11.25168357)
8,438.0,20180611041541.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:41,2.828427,FLASH,...,1545.266,1.4532,1,1,1,1,NaN,2018-06-11 04:15:41,0,POINT (-153.60532129 11.25167559)
9,439.0,20180611041551.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:51,2.828427,FLASH,...,1545.263,1.4512,1,1,1,1,NaN,2018-06-11 04:15:51,0,POINT (-153.60532147 11.25166737)
10,440.0,20180611041601.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:01,2.828427,FLASH,...,1545.248,1.4490,1,1,1,1,NaN,2018-06-11 04:16:01,0,POINT (-153.60532189 11.25165983)
11,441.0,20180611041611.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:11,2.828427,FLASH,...,1545.249,1.4485,1,1,1,1,NaN,2018-06-11 04:16:11,0,POINT (-153.60532254 11.25165416)
12,442.0,20180611041621.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:21,2.828427,FLASH,...,1545.232,1.4455,1,1,1,1,NaN,2018-06-11 04:16:21,0,POINT (-153.60532147 11.25164913)
13,443.0,20180611041631.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:31,2.828427,FLASH,...,1545.228,1.4456,1,1,1,1,NaN,2018-06-11 04:16:31,0,POINT (-153.60532064 11.2516466)
14,444.0,20180611041641.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:41,2.828427,FLASH,...,1545.241,1.4515,1,1,1,1,NaN,2018-06-11 04:16:41,0,POINT (-153.60532022 11.25164222)
15,445.0,20180611041651.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:51,2.828427,FLASH,...,1545.232,1.4506,1,1,1,1,NaN,2018-06-11 04:16:51,0,POINT (-153.60531968 11.25163773)
16,446.0,20180611041701.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:01,2.828427,FLASH,...,1545.237,1.4540,1,1,1,1,NaN,2018-06-11 04:17:01,0,POINT (-153.60532004 11.25163429)
17,447.0,20180611041711.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:11,2.828427,FLASH,...,1545.247,1.4593,1,1,1,1,NaN,2018-06-11 04:17:11,0,POINT (-153.60532082 11.25163155)
18,448.0,20180611041721.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:21,2.828427,FLASH,...,1545.228,1.4537,1,1,1,1,NaN,2018-06-11 04:17:21,0,POINT (-153.60532022 11.25162976)
19,449.0,20180611041731.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:31,2.828427,FLASH,...,1545.206,1.4478,1,1,1,1,NaN,2018-06-11 04:17:31,0,POINT (-153.60531831 11.25162916)
20,450.0,20180611041741.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:41,2.828427,FLASH,...,1545.206,1.4487,1,1,1,1,NaN,2018-06-11 04:17:41,0,POINT (-153.60531468 11.25162876)
21,451.0,20180611041751.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:51,2.828427,FLASH,...,1545.198,1.4473,1,1,1,1,NaN,2018-06-11 04:17:51,0,POINT (-153.60531062 11.25162821)
22,452.0,20180611041801.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:01,2.828427,FLASH,...,1545.190,1.4460,1,1,1,1,NaN,2018-06-11 04:18:01,0,POINT (-153.60530782 11.25162813)
23,453.0,20180611041811.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:11,2.828427,FLASH,...,1545.203,1.4546,1,1,1,1,NaN,2018-06-11 04:18:11,0,POINT (-153.60529894 11.25163219)
24,454.0,20180611041821.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:21,2.828427,FLASH,...,1545.205,1.4557,1,1,1,1,NaN,2018-06-11 04:18:21,0,POINT (-153.60529078 11.251633)
25,455.0,20180611041831.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:31,2.828427,FLASH,...,1545.222,1.4606,1,1,1,1,NaN,2018-06-11 04:18:31,0,POINT (-153.60528577 11.25163374)
26,456.0,20180611041841.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:41,2.828427,FLASH,...,1545.154,1.4391,1,1,1,1,NaN,2018-06-11 04:18:41,0,POINT (-153.60527719 11.25163777)
27,457.0,20180611041851.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:51,2.828427,FLASH,...,1545.169,1.4447,1,1,1,0,NaN,2018-06-11 04:18:51,0,POINT (-153.60527218 11.25163858)
28,458.0,20180611041901.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:01,2.828427,FLASH,...,1545.159,1.4435,1,1,1,1,NaN,2018-06-11 04:19:01,0,POINT (-153.60526246 11.25164123)
29,459.0,20180611041911.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:11,2.828427,FLASH,...,1545.252,1.4755,1,1,1,1,NaN,2018-06-11 04:19:11,0,POINT (-153.60525466 11.25164016)
30,460.0,20180611041921.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:21,2.828427,FLASH,...,1545.194,1.4549,1,1,1,1,NaN,2018-06-11 04:19:21,0,POINT (-153.60524786 11.25163778)
31,461.0,20180611041931.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:31,2.828427,FLASH,...,1545.182,1.4517,1,1,1,1,NaN,2018-06-11 04:19:31,0,POINT (-153.60524077 11.25163374)
32,462.0,20180611041941.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:41,2.828427,FLASH,...,1545.189,1.4538,1,1,1,1,NaN,2018-06-11 04:19:41,0,POINT (-153.60523183 11.25162942)
33,463.0,20180611041951.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:51,2.828427,FLASH,...,1545.155,1.4427,1,1,1,1,NaN,2018-06-11 04:19:51,0,POINT (-153.60522104 11.25162529)
34,464.0,20180611042001.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:01,2.828427,FLASH,...,1545.132,1.4345,1,1,1,1,NaN,2018-06-11 04:20:01,0,POINT (-153.60521204 11.25162354)
35,465.0,20180611042011.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:11,2.828427,FLASH,...,1545.125,1.4327,1,1,1,1,NaN,2018-06-11 04:20:11,0,POINT (-153.6052031 11.25162276)
36,466.0,20180611042021.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:21,2.828427,FLASH,...,1545.124,1.4325,1,1,1,1,NaN,2018-06-11 04:20:21,0,POINT (-153.60519493 11.25162345)
37,467.0,20180611042031.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:31,2.828427,FLASH,...,1545.121,1.4321,1,1,1,1,NaN,2018-06-11 04:20:31,0,POINT (-153.60518772 11.25162512)
38,468.0,20180611042041.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:41,2.828427,FLASH,...,1545.116,1.4319,1,1,1,1,NaN,2018-06-11 04:20:41,0,POINT (-153.60518069 11.2516276)
39,469.0,20180611042051.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:51,2.828427,FLASH,...,1545.114,1.4314,1,1,1,1,NaN,2018-06-11 04:20:51,0,POINT (-153.60517508 11.2516303)
40,470.0,20180611042101.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:01,2.828427,FLASH,...,1545.111,1.4318,1,1,1,1,NaN,2018-06-11 04:21:01,0,POINT (-153.60516984 11.25163181)
41,471.0,20180611042111.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:11,2.828427,FLASH,...,1545.107,1.4315,1,1,1,1,NaN,2018-06-11 04:21:11,0,POINT (-153.60516435 11.2516341)
42,472.0,20180611042121.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:21,2.828427,FLASH,...,1545.111,1.4350,1,1,1,1,NaN,2018-06-11 04:21:21,0,POINT (-153.6051516 11.25164437)
43,473.0,20180611042131.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:31,2.828427,FLASH,...,1545.106,1.4378,1,1,1,1,NaN,2018-06-11 04:21:31,0,POINT (-153.60514236 11.25164693)
44,474.0,20180611042141.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:41,2.828427,FLASH,...,1545.109,1.4385,1,1,1,1,NaN,2018-06-11 04:21:41,0,POINT (-153.60513384 11.25165041)
45,475.0,20180611042151.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:51,2.828427,FLASH,...,1545.102,1.4329,1,1,1,1,NaN,2018-06-11 04:21:51,0,POINT (-153.60512829 11.25165104)
46,476.0,20180611042201.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:01,2.828427,FLASH,...,1545.102,1.4327,1,1,1,1,NaN,2018-06-11 04:22:01,0,POINT (-153.60512269 11.25165186)
47,477.0,20180611042211.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:11,2.828427,FLASH,...,1545.097,1.4326,1,1,1,1,NaN,2018-06-11 04:22:11,0,POINT (-153.60511554 11.25165272)
48,478.0,20180611042221.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:21,2.828427,FLASH,...,1545.115,1.4382,1,1,1,1,NaN,2018-06-11 04:22:21,0,POINT (-153.60511047 11.25165643)

### Option 3: using Configuration class and MetadataParser class

#### Using configuration parsing

In [18]:
config = Configuration(config_file_path="../config_files/config_simple.yml")
config

{
    "general": {
        "name": "raw",
        "step_name": "open",
        "sample_data": "benthic_csv",
        "input_path": "/home/tobfer/.paidiverpy_cache/benthic_csv/images",
        "output_path": "output",
        "metadata_path": "/home/tobfer/.paidiverpy_cache/benthic_csv/metadata/metadata_benthic_csv.csv",
        "metadata_type": "CSV_FILE",
        "image_open_args": "PNG",
        "append_data_to_metadata": "/home/tobfer/.paidiverpy_cache/benthic_csv/metadata/appended_metadata_benthic_csv.csv",
        "n_jobs": 1,
        "track_changes": true,
        "rename": "datetime",
        "sampling": [
            {
                "name": "sampling",
                "step_name": "sampling",
                "test": false,
                "params": {
                    "value": 0.1,
                    "raise_error": false
                },
                "mode": "percent"
            }
        ],
        "convert": [
            {
                "name": "convert",
                "step_name": "convert",
                "test": false,
                "params": {
                    "output_bits": 8,
                    "raise_error": false
                },
                "mode": "bits"
            },
            {
                "name": "convert",
                "step_name": "convert",
                "test": false,
                "params": {
                    "to": "gray",
                    "channel_selector": 0,
                    "raise_error": false
                },
                "mode": "to"
            }
        ]
    },
    "steps": []
}


In this case, yu will not have access to the metadata, as it was not parsed yet

#### Parse only the metadata

In [19]:
# You need to pass the configuration file
metadata = MetadataParser(config=config)
metadata

,ID,image-filename,XResolution,YResolution,ExposureTime,FNumber,ISO,image-datetime,MaxApertureValue,WhiteBalance,...,speed_of_sound_m_s,temperature_c,positioning_ok,attitude_ok,depth_ok,altitude_ok,X,phototime,flag,point
0,430.0,20180611041421.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:21,2.828427,FLASH,...,1545.388,1.5059,1,1,1,1,NaN,2018-06-11 04:14:21,0,POINT (-153.60531587 11.25172554)
1,431.0,20180611041431.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:31,2.828427,FLASH,...,1545.447,1.5236,1,1,1,1,NaN,2018-06-11 04:14:31,0,POINT (-153.60531372 11.25171832)
2,432.0,20180611041441.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:41,2.828427,FLASH,...,1545.452,1.5234,1,1,1,1,NaN,2018-06-11 04:14:41,0,POINT (-153.60531259 11.2517135)
3,433.0,20180611041451.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:51,2.828427,FLASH,...,1545.363,1.4911,1,1,1,1,NaN,2018-06-11 04:14:51,0,POINT (-153.60531313 11.25170837)
4,434.0,20180611041501.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:01,2.828427,FLASH,...,1545.324,1.4747,1,1,1,1,NaN,2018-06-11 04:15:01,0,POINT (-153.60531414 11.25170299)
5,435.0,20180611041511.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:11,2.828427,FLASH,...,1545.298,1.4635,1,1,1,1,NaN,2018-06-11 04:15:11,0,POINT (-153.60531664 11.25169768)
6,436.0,20180611041521.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:21,2.828427,FLASH,...,1545.315,1.4697,1,1,1,1,NaN,2018-06-11 04:15:21,0,POINT (-153.6053176 11.25169125)
7,437.0,20180611041531.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:31,2.828427,FLASH,...,1545.326,1.4727,1,1,1,1,NaN,2018-06-11 04:15:31,0,POINT (-153.60532046 11.25168357)
8,438.0,20180611041541.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:41,2.828427,FLASH,...,1545.266,1.4532,1,1,1,1,NaN,2018-06-11 04:15:41,0,POINT (-153.60532129 11.25167559)
9,439.0,20180611041551.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:51,2.828427,FLASH,...,1545.263,1.4512,1,1,1,1,NaN,2018-06-11 04:15:51,0,POINT (-153.60532147 11.25166737)
10,440.0,20180611041601.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:01,2.828427,FLASH,...,1545.248,1.4490,1,1,1,1,NaN,2018-06-11 04:16:01,0,POINT (-153.60532189 11.25165983)
11,441.0,20180611041611.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:11,2.828427,FLASH,...,1545.249,1.4485,1,1,1,1,NaN,2018-06-11 04:16:11,0,POINT (-153.60532254 11.25165416)
12,442.0,20180611041621.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:21,2.828427,FLASH,...,1545.232,1.4455,1,1,1,1,NaN,2018-06-11 04:16:21,0,POINT (-153.60532147 11.25164913)
13,443.0,20180611041631.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:31,2.828427,FLASH,...,1545.228,1.4456,1,1,1,1,NaN,2018-06-11 04:16:31,0,POINT (-153.60532064 11.2516466)
14,444.0,20180611041641.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:41,2.828427,FLASH,...,1545.241,1.4515,1,1,1,1,NaN,2018-06-11 04:16:41,0,POINT (-153.60532022 11.25164222)
15,445.0,20180611041651.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:51,2.828427,FLASH,...,1545.232,1.4506,1,1,1,1,NaN,2018-06-11 04:16:51,0,POINT (-153.60531968 11.25163773)
16,446.0,20180611041701.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:01,2.828427,FLASH,...,1545.237,1.4540,1,1,1,1,NaN,2018-06-11 04:17:01,0,POINT (-153.60532004 11.25163429)
17,447.0,20180611041711.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:11,2.828427,FLASH,...,1545.247,1.4593,1,1,1,1,NaN,2018-06-11 04:17:11,0,POINT (-153.60532082 11.25163155)
18,448.0,20180611041721.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:21,2.828427,FLASH,...,1545.228,1.4537,1,1,1,1,NaN,2018-06-11 04:17:21,0,POINT (-153.60532022 11.25162976)
19,449.0,20180611041731.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:31,2.828427,FLASH,...,1545.206,1.4478,1,1,1,1,NaN,2018-06-11 04:17:31,0,POINT (-153.60531831 11.25162916)
20,450.0,20180611041741.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:41,2.828427,FLASH,...,1545.206,1.4487,1,1,1,1,NaN,2018-06-11 04:17:41,0,POINT (-153.60531468 11.25162876)
21,451.0,20180611041751.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:51,2.828427,FLASH,...,1545.198,1.4473,1,1,1,1,NaN,2018-06-11 04:17:51,0,POINT (-153.60531062 11.25162821)
22,452.0,20180611041801.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:01,2.828427,FLASH,...,1545.190,1.4460,1,1,1,1,NaN,2018-06-11 04:18:01,0,POINT (-153.60530782 11.25162813)
23,453.0,20180611041811.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:11,2.828427,FLASH,...,1545.203,1.4546,1,1,1,1,NaN,2018-06-11 04:18:11,0,POINT (-153.60529894 11.25163219)
24,454.0,20180611041821.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:21,2.828427,FLASH,...,1545.205,1.4557,1,1,1,1,NaN,2018-06-11 04:18:21,0,POINT (-153.60529078 11.251633)
25,455.0,20180611041831.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:31,2.828427,FLASH,...,1545.222,1.4606,1,1,1,1,NaN,2018-06-11 04:18:31,0,POINT (-153.60528577 11.25163374)
26,456.0,20180611041841.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:41,2.828427,FLASH,...,1545.154,1.4391,1,1,1,1,NaN,2018-06-11 04:18:41,0,POINT (-153.60527719 11.25163777)
27,457.0,20180611041851.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:51,2.828427,FLASH,...,1545.169,1.4447,1,1,1,0,NaN,2018-06-11 04:18:51,0,POINT (-153.60527218 11.25163858)
28,458.0,20180611041901.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:01,2.828427,FLASH,...,1545.159,1.4435,1,1,1,1,NaN,2018-06-11 04:19:01,0,POINT (-153.60526246 11.25164123)
29,459.0,20180611041911.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:11,2.828427,FLASH,...,1545.252,1.4755,1,1,1,1,NaN,2018-06-11 04:19:11,0,POINT (-153.60525466 11.25164016)
30,460.0,20180611041921.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:21,2.828427,FLASH,...,1545.194,1.4549,1,1,1,1,NaN,2018-06-11 04:19:21,0,POINT (-153.60524786 11.25163778)
31,461.0,20180611041931.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:31,2.828427,FLASH,...,1545.182,1.4517,1,1,1,1,NaN,2018-06-11 04:19:31,0,POINT (-153.60524077 11.25163374)
32,462.0,20180611041941.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:41,2.828427,FLASH,...,1545.189,1.4538,1,1,1,1,NaN,2018-06-11 04:19:41,0,POINT (-153.60523183 11.25162942)
33,463.0,20180611041951.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:51,2.828427,FLASH,...,1545.155,1.4427,1,1,1,1,NaN,2018-06-11 04:19:51,0,POINT (-153.60522104 11.25162529)
34,464.0,20180611042001.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:01,2.828427,FLASH,...,1545.132,1.4345,1,1,1,1,NaN,2018-06-11 04:20:01,0,POINT (-153.60521204 11.25162354)
35,465.0,20180611042011.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:11,2.828427,FLASH,...,1545.125,1.4327,1,1,1,1,NaN,2018-06-11 04:20:11,0,POINT (-153.6052031 11.25162276)
36,466.0,20180611042021.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:21,2.828427,FLASH,...,1545.124,1.4325,1,1,1,1,NaN,2018-06-11 04:20:21,0,POINT (-153.60519493 11.25162345)
37,467.0,20180611042031.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:31,2.828427,FLASH,...,1545.121,1.4321,1,1,1,1,NaN,2018-06-11 04:20:31,0,POINT (-153.60518772 11.25162512)
38,468.0,20180611042041.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:41,2.828427,FLASH,...,1545.116,1.4319,1,1,1,1,NaN,2018-06-11 04:20:41,0,POINT (-153.60518069 11.2516276)
39,469.0,20180611042051.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:51,2.828427,FLASH,...,1545.114,1.4314,1,1,1,1,NaN,2018-06-11 04:20:51,0,POINT (-153.60517508 11.2516303)
40,470.0,20180611042101.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:01,2.828427,FLASH,...,1545.111,1.4318,1,1,1,1,NaN,2018-06-11 04:21:01,0,POINT (-153.60516984 11.25163181)
41,471.0,20180611042111.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:11,2.828427,FLASH,...,1545.107,1.4315,1,1,1,1,NaN,2018-06-11 04:21:11,0,POINT (-153.60516435 11.2516341)
42,472.0,20180611042121.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:21,2.828427,FLASH,...,1545.111,1.4350,1,1,1,1,NaN,2018-06-11 04:21:21,0,POINT (-153.6051516 11.25164437)
43,473.0,20180611042131.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:31,2.828427,FLASH,...,1545.106,1.4378,1,1,1,1,NaN,2018-06-11 04:21:31,0,POINT (-153.60514236 11.25164693)
44,474.0,20180611042141.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:41,2.828427,FLASH,...,1545.109,1.4385,1,1,1,1,NaN,2018-06-11 04:21:41,0,POINT (-153.60513384 11.25165041)
45,475.0,20180611042151.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:51,2.828427,FLASH,...,1545.102,1.4329,1,1,1,1,NaN,2018-06-11 04:21:51,0,POINT (-153.60512829 11.25165104)
46,476.0,20180611042201.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:01,2.828427,FLASH,...,1545.102,1.4327,1,1,1,1,NaN,2018-06-11 04:22:01,0,POINT (-153.60512269 11.25165186)
47,477.0,20180611042211.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:11,2.828427,FLASH,...,1545.097,1.4326,1,1,1,1,NaN,2018-06-11 04:22:11,0,POINT (-153.60511554 11.25165272)
48,478.0,20180611042221.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:21,2.828427,FLASH,...,1545.115,1.4382,1,1,1,1,NaN,2018-06-11 04:22:21,0,POINT (-153.60511047 11.25165643)