## Open config file and metadata

This example shows how to handle and parse metadata and configuration files using paidiverpy package

## Import dependencies

In [1]:
%load_ext autoreload
%autoreload 2
from paidiverpy import Paidiverpy
from paidiverpy.config import Configuration
from paidiverpy.metadata_parser import MetadataParser
from paidiverpy.open_layer import OpenLayer

## Loading metadata and configuration files

There are several ways to load and parse the metadata and the configuration file:

- Option 1: using the Paidiverpy class
- Option 2: using other processing classes, like OpenLayer#
- Option 3: using Configuration class and MetadataParser class

### Option 1: Using Paidiverpy class

In [2]:
# Instantiate the class
# You may need to change the parameters on the config_simple.yml file for the correct paths on your computer
paidiverpy = Paidiverpy(config_file_path="../config_files/config_simple.yml")

In [3]:
# See the type of config
type(paidiverpy.config)

paidiverpy.config.configuration.Configuration

In [4]:
# Print config as json
paidiverpy.config

{
    "general": {
        "name": "raw",
        "step_name": "open",
        "sample_data": "benthic_csv",
        "input_path": "/home/tobfer/.paidiverpy_cache/benthic_csv/images",
        "output_path": "output",
        "metadata_path": "/home/tobfer/.paidiverpy_cache/benthic_csv/metadata/metadata_benthic_csv.csv",
        "metadata_type": "CSV_FILE",
        "image_open_args": "PNG",
        "append_data_to_metadata": "/home/tobfer/.paidiverpy_cache/benthic_csv/metadata/appended_metadata_benthic_csv.csv",
        "n_jobs": 1,
        "track_changes": true,
        "rename": "datetime",
        "sampling": [
            {
                "name": "sampling",
                "step_name": "sampling",
                "test": false,
                "params": {
                    "value": 0.1,
                    "raise_error": false
                },
                "mode": "percent"
            }
        ],
        "convert": [
            {
                "name": "convert",
                "step_name": "convert",
                "test": false,
                "params": {
                    "output_bits": 8,
                    "raise_error": false
                },
                "mode": "bits"
            },
            {
                "name": "convert",
                "step_name": "convert",
                "test": false,
                "params": {
                    "to": "gray",
                    "channel_selector": 0,
                    "raise_error": false
                },
                "mode": "to"
            }
        ]
    },
    "steps": []
}

In [5]:
# See metadata information
paidiverpy.get_metadata()

<xarray.DataArray (filename: 49)> Size: 392B
array([{'ID': 430.0, 'filename': '20180611041421.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:14:21'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 426737, 'image-longitude': -153.60531587, 'image-latitude': 11.25172554, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.937, 'image-camera-pitch-degrees': 2.287, 'heading_deg': 90.751, 'cog_deg': 188.426969021481, 'image-depth': 5203.744, 'sog_m_s': 0.0272946881279124, 'time_unix_seconds': 1528690461.02041, 'conductivity': 3.21279, 'depth_m.1': 5203.744, 'pressure_psi': 7688.29530138297, 'salinity': 34.6773, 'speed_of_sound_m_s': 1545.388, 'temperature_c': 1.5059, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:14:21', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 431.0, 'filename': '20180611041431.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:14:31'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 426916, 'image-longitude': -153.60531372, 'image-latitude': 11.25171832, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 1.326, 'image-camera-pitch-degrees': 1.993, 'heading_deg': 89.866, 'cog_deg': 221.63353933657, 'image-depth': 5203.744, 'sog_m_s': 0.0240831891575846, 'time_unix_seconds': 1528690471.02991, 'conductivity': 3.21329, 'depth_m.1': 5203.744, 'pressure_psi': 7688.29530138297, 'salinity': 34.6647, 'speed_of_sound_m_s': 1545.447, 'temperature_c': 1.5236, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:14:31', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 432.0, 'filename': '20180611041441.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:14:41'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 427094, 'image-longitude': -153.60531259, 'image-latitude': 11.2517135, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.577, 'image-camera-pitch-degrees': 1.59, 'heading_deg': 90.486, 'cog_deg': 226.847610265995, 'image-depth': 5203.785, 'sog_m_s': 0.0219317121994613, 'time_unix_seconds': 1528690481.01456, 'conductivity': 3.21359, 'depth_m.1': 5203.785, 'pressure_psi': 7688.35766761031, 'salinity': 34.6686, 'speed_of_sound_m_s': 1545.452, 'temperature_c': 1.5234, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:14:41', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 433.0, 'filename': '20180611041451.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:14:51'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 427274, 'image-longitude': -153.60531313, 'image-latitude': 11.25170837, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.841, 'image-camera-pitch-degrees': 2.262, 'heading_deg': 90.468, 'cog_deg': 232.125016348902, 'image-depth': 5203.724, 'sog_m_s': 0.0114017542509914, 'time_unix_seconds': 1528690491.06994, 'conductivity': 3.21395, 'depth_m.1': 5203.724, 'pressure_psi': 7688.26484345799, 'salinity': 34.7067, 'speed_of_sound_m_s': 1545.363, 'temperature_c': 1.4911, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:14:51', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 434.0, 'filename': '20180611041501.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:15:01'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 427452, 'image-longitude': -153.60531414, 'image-latitude': 11.25170299, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 1.01, 'image-camera-pitch-degrees': 1.545, 'heading_deg': 89.988, 'cog_deg': 245.772254682046, 'image-depth': 5203.703, 'sog_m_s': 0.0219317121994613, 'time_unix_seconds': 1528690501.01889, 'conductivity': 3.21446, 'depth_m.1': 5203.703, 'pressure_psi': 7688.234385533, 'salinity': 34.7302, 'speed_of_sound_m_s': 1545.324, 'temperature_c': 1.4747, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:15:01', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 435.0, 'filename': '20180611041511.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:15:11'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 427630, 'image-longitude': -153.60531664, 'image-latitude': 11.25169768, 'image-altitude-meters': 1.6, 'image-camera-roll-degrees': 0.503, 'image-camera-pitch-degrees': 1.394, 'heading_deg': 90.419, 'cog_deg': 228.012787504183, 'image-depth': 5203.653, 'sog_m_s': 0.0134536240470737, 'time_unix_seconds': 1528690511.01836, 'conductivity': 3.2149, 'depth_m.1': 5203.653, 'pressure_psi': 7688.15896590924, 'salinity': 34.7474, 'speed_of_sound_m_s': 1545.298, 'temperature_c': 1.4635, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:15:11', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 436.0, 'filename': '20180611041521.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:15:21'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 427808, 'image-longitude': -153.6053176, 'image-latitude': 11.25169125, 'image-altitude-meters': 1.6, 'image-camera-roll-degrees': 0.725, 'image-camera-pitch-degrees': 2.818, 'heading_deg': 90.627, 'cog_deg': 270.0, 'image-depth': 5203.653, 'sog_m_s': 0.014, 'time_unix_seconds': 1528690521.00569, 'conductivity': 3.21489, 'depth_m.1': 5203.653, 'pressure_psi': 7688.15896590924, 'salinity': 34.7407, 'speed_of_sound_m_s': 1545.315, 'temperature_c': 1.4697, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:15:21', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 437.0, 'filename': '20180611041531.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:15:31'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 427988, 'image-longitude': -153.60532046, 'image-latitude': 11.25168357, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.7, 'image-camera-pitch-degrees': 3.255, 'heading_deg': 89.979, 'cog_deg': 265.914383220025, 'image-depth': 5203.806, 'sog_m_s': 0.0140356688476182, 'time_unix_seconds': 1528690531.0678, 'conductivity': 3.21483, 'depth_m.1': 5203.806, 'pressure_psi': 7688.38667515791, 'salinity': 34.7368, 'speed_of_sound_m_s': 1545.326, 'temperature_c': 1.4727, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:15:31', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 438.0, 'filename': '20180611041541.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:15:41'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 428166, 'image-longitude': -153.60532129, 'image-latitude': 11.25167559, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.845, 'image-camera-pitch-degrees': 1.886, 'heading_deg': 90.377, 'cog_deg': 259.380344723845, 'image-depth': 5203.724, 'sog_m_s': 0.0162788205960997, 'time_unix_seconds': 1528690541.05393, 'conductivity': 3.21469, 'depth_m.1': 5203.724, 'pressure_psi': 7688.26484345799, 'salinity': 34.7556, 'speed_of_sound_m_s': 1545.266, 'temperature_c': 1.4532, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:15:41', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 439.0, 'filename': '20180611041551.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:15:51'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 428344, 'image-longitude': -153.60532147, 'image-latitude': 11.25166737, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.731, 'image-camera-pitch-degrees': 2.273, 'heading_deg': 90.602, 'cog_deg': 298.072486935853, 'image-depth': 5203.756, 'sog_m_s': 0.017, 'time_unix_seconds': 1528690551.05698, 'conductivity': 3.21481, 'depth_m.1': 5203.756, 'pressure_psi': 7688.31270591153, 'salinity': 34.759, 'speed_of_sound_m_s': 1545.263, 'temperature_c': 1.4512, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:15:51', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 440.0, 'filename': '20180611041601.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:16:01'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 428522, 'image-longitude': -153.60532189, 'image-latitude': 11.25165983, 'image-altitude-meters': 1.6, 'image-camera-roll-degrees': 0.837, 'image-camera-pitch-degrees': 1.101, 'heading_deg': 90.093, 'cog_deg': 294.775140568832, 'image-depth': 5203.694, 'sog_m_s': 0.0143178210632764, 'time_unix_seconds': 1528690561.01589, 'conductivity': 3.21441, 'depth_m.1': 5203.694, 'pressure_psi': 7688.22133213658, 'salinity': 34.7566, 'speed_of_sound_m_s': 1545.248, 'temperature_c': 1.449, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:16:01', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 441.0, 'filename': '20180611041611.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:16:11'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 428700, 'image-longitude': -153.60532254, 'image-latitude': 11.25165416, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.966, 'image-camera-pitch-degrees': 1.406, 'heading_deg': 90.64, 'cog_deg': 310.236358309274, 'image-depth': 5203.817, 'sog_m_s': 0.0170293863659264, 'time_unix_seconds': 1528690571.00514, 'conductivity': 3.21436, 'depth_m.1': 5203.817, 'pressure_psi': 7688.40407968647, 'salinity': 34.7564, 'speed_of_sound_m_s': 1545.249, 'temperature_c': 1.4485, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:16:11', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 442.0, 'filename': '20180611041621.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:16:21'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 428879, 'image-longitude': -153.60532147, 'image-latitude': 11.25164913, 'image-altitude-meters': 1.6, 'image-camera-roll-degrees': 0.432, 'image-camera-pitch-degrees': 1.34, 'heading_deg': 90.433, 'cog_deg': 335.556045219583, 'image-depth': 5203.703, 'sog_m_s': 0.0120830459735946, 'time_unix_seconds': 1528690581.04368, 'conductivity': 3.21398, 'depth_m.1': 5203.703, 'pressure_psi': 7688.234385533, 'salinity': 34.755, 'speed_of_sound_m_s': 1545.232, 'temperature_c': 1.4455, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:16:21', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 443.0, 'filename': '20180611041631.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:16:31'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 429057, 'image-longitude': -153.60532064, 'image-latitude': 11.2516466, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.701, 'image-camera-pitch-degrees': 2.646, 'heading_deg': 90.561, 'cog_deg': 2.12109639666145, 'image-depth': 5203.735, 'sog_m_s': 0.0270185121722126, 'time_unix_seconds': 1528690591.02032, 'conductivity': 3.21372, 'depth_m.1': 5203.735, 'pressure_psi': 7688.28224798655, 'salinity': 34.7518, 'speed_of_sound_m_s': 1545.228, 'temperature_c': 1.4456, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:16:31', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 444.0, 'filename': '20180611041641.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:16:41'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 429235, 'image-longitude': -153.60532022, 'image-latitude': 11.25164222, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.705, 'image-camera-pitch-degrees': 3.037, 'heading_deg': 90.376, 'cog_deg': 353.418055344822, 'image-depth': 5203.766, 'sog_m_s': 0.0261725046566048, 'time_unix_seconds': 1528690601.0077, 'conductivity': 3.2134, 'depth_m.1': 5203.766, 'pressure_psi': 7688.32720968533, 'salinity': 34.7417, 'speed_of_sound_m_s': 1545.241, 'temperature_c': 1.4515, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:16:41', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 445.0, 'filename': '20180611041651.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:16:51'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 429415, 'image-longitude': -153.60531968, 'image-latitude': 11.25163773, 'image-altitude-meters': 1.6, 'image-camera-roll-degrees': 1.092, 'image-camera-pitch-degrees': 2.186, 'heading_deg': 90.058, 'cog_deg': 337.750976342788, 'image-depth': 5203.724, 'sog_m_s': 0.0237697286480094, 'time_unix_seconds': 1528690611.06968, 'conductivity': 3.21309, 'depth_m.1': 5203.724, 'pressure_psi': 7688.26484345799, 'salinity': 34.739, 'speed_of_sound_m_s': 1545.232, 'temperature_c': 1.4506, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:16:51', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 446.0, 'filename': '20180611041701.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:17:01'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 429593, 'image-longitude': -153.60532004, 'image-latitude': 11.25163429, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.536, 'image-camera-pitch-degrees': 1.977, 'heading_deg': 90.765, 'cog_deg': 338.198590513648, 'image-depth': 5203.777, 'sog_m_s': 0.0269258240356725, 'time_unix_seconds': 1528690621.00762, 'conductivity': 3.21271, 'depth_m.1': 5203.777, 'pressure_psi': 7688.34316383651, 'salinity': 34.7307, 'speed_of_sound_m_s': 1545.237, 'temperature_c': 1.454, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:17:01', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 447.0, 'filename': '20180611041711.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:17:11'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 429771, 'image-longitude': -153.60532082, 'image-latitude': 11.25163155, 'image-altitude-meters': 1.6, 'image-camera-roll-degrees': 0.904, 'image-camera-pitch-degrees': 0.347, 'heading_deg': 90.316, 'cog_deg': 356.531770741083, 'image-depth': 5203.715, 'sog_m_s': 0.0330605505096331, 'time_unix_seconds': 1528690631.02903, 'conductivity': 3.21248, 'depth_m.1': 5203.715, 'pressure_psi': 7688.25179006156, 'salinity': 34.7223, 'speed_of_sound_m_s': 1545.247, 'temperature_c': 1.4593, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:17:11', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 448.0, 'filename': '20180611041721.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:17:21'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 429949, 'image-longitude': -153.60532022, 'image-latitude': 11.25162976, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.933, 'image-camera-pitch-degrees': 1.649, 'heading_deg': 90.269, 'cog_deg': 25.1148348861446, 'image-depth': 5203.756, 'sog_m_s': 0.0353411940941446, 'time_unix_seconds': 1528690641.01444, 'conductivity': 3.21221, 'depth_m.1': 5203.756, 'pressure_psi': 7688.31270591153, 'salinity': 34.725, 'speed_of_sound_m_s': 1545.228, 'temperature_c': 1.4537, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:17:21', 'flag': 0, 'point': <POINT (-153.605 11.252)>},

In [6]:
# see metadata info as a table
paidiverpy.get_metadata(output_format="pandas")

,ID,filename,XResolution,YResolution,ExposureTime,FNumber,ISO,image-datetime,MaxApertureValue,WhiteBalance,...,speed_of_sound_m_s,temperature_c,positioning_ok,attitude_ok,depth_ok,altitude_ok,X,phototime,flag,point
0,430.0,20180611041421.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:21,2.828427,FLASH,...,1545.388,1.5059,1,1,1,1,NaN,2018-06-11 04:14:21,0,POINT (-153.60531587 11.25172554)
1,431.0,20180611041431.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:31,2.828427,FLASH,...,1545.447,1.5236,1,1,1,1,NaN,2018-06-11 04:14:31,0,POINT (-153.60531372 11.25171832)
2,432.0,20180611041441.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:41,2.828427,FLASH,...,1545.452,1.5234,1,1,1,1,NaN,2018-06-11 04:14:41,0,POINT (-153.60531259 11.2517135)
3,433.0,20180611041451.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:51,2.828427,FLASH,...,1545.363,1.4911,1,1,1,1,NaN,2018-06-11 04:14:51,0,POINT (-153.60531313 11.25170837)
4,434.0,20180611041501.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:01,2.828427,FLASH,...,1545.324,1.4747,1,1,1,1,NaN,2018-06-11 04:15:01,0,POINT (-153.60531414 11.25170299)
5,435.0,20180611041511.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:11,2.828427,FLASH,...,1545.298,1.4635,1,1,1,1,NaN,2018-06-11 04:15:11,0,POINT (-153.60531664 11.25169768)
6,436.0,20180611041521.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:21,2.828427,FLASH,...,1545.315,1.4697,1,1,1,1,NaN,2018-06-11 04:15:21,0,POINT (-153.6053176 11.25169125)
7,437.0,20180611041531.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:31,2.828427,FLASH,...,1545.326,1.4727,1,1,1,1,NaN,2018-06-11 04:15:31,0,POINT (-153.60532046 11.25168357)
8,438.0,20180611041541.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:41,2.828427,FLASH,...,1545.266,1.4532,1,1,1,1,NaN,2018-06-11 04:15:41,0,POINT (-153.60532129 11.25167559)
9,439.0,20180611041551.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:51,2.828427,FLASH,...,1545.263,1.4512,1,1,1,1,NaN,2018-06-11 04:15:51,0,POINT (-153.60532147 11.25166737)
10,440.0,20180611041601.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:01,2.828427,FLASH,...,1545.248,1.4490,1,1,1,1,NaN,2018-06-11 04:16:01,0,POINT (-153.60532189 11.25165983)
11,441.0,20180611041611.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:11,2.828427,FLASH,...,1545.249,1.4485,1,1,1,1,NaN,2018-06-11 04:16:11,0,POINT (-153.60532254 11.25165416)
12,442.0,20180611041621.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:21,2.828427,FLASH,...,1545.232,1.4455,1,1,1,1,NaN,2018-06-11 04:16:21,0,POINT (-153.60532147 11.25164913)
13,443.0,20180611041631.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:31,2.828427,FLASH,...,1545.228,1.4456,1,1,1,1,NaN,2018-06-11 04:16:31,0,POINT (-153.60532064 11.2516466)
14,444.0,20180611041641.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:41,2.828427,FLASH,...,1545.241,1.4515,1,1,1,1,NaN,2018-06-11 04:16:41,0,POINT (-153.60532022 11.25164222)
15,445.0,20180611041651.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:51,2.828427,FLASH,...,1545.232,1.4506,1,1,1,1,NaN,2018-06-11 04:16:51,0,POINT (-153.60531968 11.25163773)
16,446.0,20180611041701.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:01,2.828427,FLASH,...,1545.237,1.4540,1,1,1,1,NaN,2018-06-11 04:17:01,0,POINT (-153.60532004 11.25163429)
17,447.0,20180611041711.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:11,2.828427,FLASH,...,1545.247,1.4593,1,1,1,1,NaN,2018-06-11 04:17:11,0,POINT (-153.60532082 11.25163155)
18,448.0,20180611041721.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:21,2.828427,FLASH,...,1545.228,1.4537,1,1,1,1,NaN,2018-06-11 04:17:21,0,POINT (-153.60532022 11.25162976)
19,449.0,20180611041731.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:31,2.828427,FLASH,...,1545.206,1.4478,1,1,1,1,NaN,2018-06-11 04:17:31,0,POINT (-153.60531831 11.25162916)
20,450.0,20180611041741.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:41,2.828427,FLASH,...,1545.206,1.4487,1,1,1,1,NaN,2018-06-11 04:17:41,0,POINT (-153.60531468 11.25162876)
21,451.0,20180611041751.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:51,2.828427,FLASH,...,1545.198,1.4473,1,1,1,1,NaN,2018-06-11 04:17:51,0,POINT (-153.60531062 11.25162821)
22,452.0,20180611041801.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:01,2.828427,FLASH,...,1545.190,1.4460,1,1,1,1,NaN,2018-06-11 04:18:01,0,POINT (-153.60530782 11.25162813)
23,453.0,20180611041811.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:11,2.828427,FLASH,...,1545.203,1.4546,1,1,1,1,NaN,2018-06-11 04:18:11,0,POINT (-153.60529894 11.25163219)
24,454.0,20180611041821.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:21,2.828427,FLASH,...,1545.205,1.4557,1,1,1,1,NaN,2018-06-11 04:18:21,0,POINT (-153.60529078 11.251633)
25,455.0,20180611041831.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:31,2.828427,FLASH,...,1545.222,1.4606,1,1,1,1,NaN,2018-06-11 04:18:31,0,POINT (-153.60528577 11.25163374)
26,456.0,20180611041841.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:41,2.828427,FLASH,...,1545.154,1.4391,1,1,1,1,NaN,2018-06-11 04:18:41,0,POINT (-153.60527719 11.25163777)
27,457.0,20180611041851.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:51,2.828427,FLASH,...,1545.169,1.4447,1,1,1,0,NaN,2018-06-11 04:18:51,0,POINT (-153.60527218 11.25163858)
28,458.0,20180611041901.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:01,2.828427,FLASH,...,1545.159,1.4435,1,1,1,1,NaN,2018-06-11 04:19:01,0,POINT (-153.60526246 11.25164123)
29,459.0,20180611041911.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:11,2.828427,FLASH,...,1545.252,1.4755,1,1,1,1,NaN,2018-06-11 04:19:11,0,POINT (-153.60525466 11.25164016)
30,460.0,20180611041921.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:21,2.828427,FLASH,...,1545.194,1.4549,1,1,1,1,NaN,2018-06-11 04:19:21,0,POINT (-153.60524786 11.25163778)
31,461.0,20180611041931.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:31,2.828427,FLASH,...,1545.182,1.4517,1,1,1,1,NaN,2018-06-11 04:19:31,0,POINT (-153.60524077 11.25163374)
32,462.0,20180611041941.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:41,2.828427,FLASH,...,1545.189,1.4538,1,1,1,1,NaN,2018-06-11 04:19:41,0,POINT (-153.60523183 11.25162942)
33,463.0,20180611041951.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:51,2.828427,FLASH,...,1545.155,1.4427,1,1,1,1,NaN,2018-06-11 04:19:51,0,POINT (-153.60522104 11.25162529)
34,464.0,20180611042001.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:01,2.828427,FLASH,...,1545.132,1.4345,1,1,1,1,NaN,2018-06-11 04:20:01,0,POINT (-153.60521204 11.25162354)
35,465.0,20180611042011.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:11,2.828427,FLASH,...,1545.125,1.4327,1,1,1,1,NaN,2018-06-11 04:20:11,0,POINT (-153.6052031 11.25162276)
36,466.0,20180611042021.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:21,2.828427,FLASH,...,1545.124,1.4325,1,1,1,1,NaN,2018-06-11 04:20:21,0,POINT (-153.60519493 11.25162345)
37,467.0,20180611042031.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:31,2.828427,FLASH,...,1545.121,1.4321,1,1,1,1,NaN,2018-06-11 04:20:31,0,POINT (-153.60518772 11.25162512)
38,468.0,20180611042041.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:41,2.828427,FLASH,...,1545.116,1.4319,1,1,1,1,NaN,2018-06-11 04:20:41,0,POINT (-153.60518069 11.2516276)
39,469.0,20180611042051.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:51,2.828427,FLASH,...,1545.114,1.4314,1,1,1,1,NaN,2018-06-11 04:20:51,0,POINT (-153.60517508 11.2516303)
40,470.0,20180611042101.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:01,2.828427,FLASH,...,1545.111,1.4318,1,1,1,1,NaN,2018-06-11 04:21:01,0,POINT (-153.60516984 11.25163181)
41,471.0,20180611042111.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:11,2.828427,FLASH,...,1545.107,1.4315,1,1,1,1,NaN,2018-06-11 04:21:11,0,POINT (-153.60516435 11.2516341)
42,472.0,20180611042121.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:21,2.828427,FLASH,...,1545.111,1.4350,1,1,1,1,NaN,2018-06-11 04:21:21,0,POINT (-153.6051516 11.25164437)
43,473.0,20180611042131.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:31,2.828427,FLASH,...,1545.106,1.4378,1,1,1,1,NaN,2018-06-11 04:21:31,0,POINT (-153.60514236 11.25164693)
44,474.0,20180611042141.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:41,2.828427,FLASH,...,1545.109,1.4385,1,1,1,1,NaN,2018-06-11 04:21:41,0,POINT (-153.60513384 11.25165041)
45,475.0,20180611042151.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:51,2.828427,FLASH,...,1545.102,1.4329,1,1,1,1,NaN,2018-06-11 04:21:51,0,POINT (-153.60512829 11.25165104)
46,476.0,20180611042201.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:01,2.828427,FLASH,...,1545.102,1.4327,1,1,1,1,NaN,2018-06-11 04:22:01,0,POINT (-153.60512269 11.25165186)
47,477.0,20180611042211.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:11,2.828427,FLASH,...,1545.097,1.4326,1,1,1,1,NaN,2018-06-11 04:22:11,0,POINT (-153.60511554 11.25165272)
48,478.0,20180611042221.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:21,2.828427,FLASH,...,1545.115,1.4382,1,1,1,1,NaN,2018-06-11 04:22:21,0,POINT (-153.60511047 11.25165643)

### Option 2: Using other processing classes, like OpenLayer

In [7]:
open_layer = OpenLayer(config_file_path="../config_files/config_simple.yml")

In [8]:
# Print config as json
open_layer.config

{
    "general": {
        "name": "raw",
        "step_name": "open",
        "sample_data": "benthic_csv",
        "input_path": "/home/tobfer/.paidiverpy_cache/benthic_csv/images",
        "output_path": "output",
        "metadata_path": "/home/tobfer/.paidiverpy_cache/benthic_csv/metadata/metadata_benthic_csv.csv",
        "metadata_type": "CSV_FILE",
        "image_open_args": "PNG",
        "append_data_to_metadata": "/home/tobfer/.paidiverpy_cache/benthic_csv/metadata/appended_metadata_benthic_csv.csv",
        "n_jobs": 1,
        "track_changes": true,
        "rename": "datetime",
        "sampling": [
            {
                "name": "sampling",
                "step_name": "sampling",
                "test": false,
                "params": {
                    "value": 0.1,
                    "raise_error": false
                },
                "mode": "percent"
            }
        ],
        "convert": [
            {
                "name": "convert",
                "step_name": "convert",
                "test": false,
                "params": {
                    "output_bits": 8,
                    "raise_error": false
                },
                "mode": "bits"
            },
            {
                "name": "convert",
                "step_name": "convert",
                "test": false,
                "params": {
                    "to": "gray",
                    "channel_selector": 0,
                    "raise_error": false
                },
                "mode": "to"
            }
        ]
    },
    "steps": []
}

In [9]:
# See metadata information
open_layer.get_metadata(output_format="pandas")

,ID,filename,XResolution,YResolution,ExposureTime,FNumber,ISO,image-datetime,MaxApertureValue,WhiteBalance,...,speed_of_sound_m_s,temperature_c,positioning_ok,attitude_ok,depth_ok,altitude_ok,X,phototime,flag,point
0,430.0,20180611041421.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:21,2.828427,FLASH,...,1545.388,1.5059,1,1,1,1,NaN,2018-06-11 04:14:21,0,POINT (-153.60531587 11.25172554)
1,431.0,20180611041431.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:31,2.828427,FLASH,...,1545.447,1.5236,1,1,1,1,NaN,2018-06-11 04:14:31,0,POINT (-153.60531372 11.25171832)
2,432.0,20180611041441.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:41,2.828427,FLASH,...,1545.452,1.5234,1,1,1,1,NaN,2018-06-11 04:14:41,0,POINT (-153.60531259 11.2517135)
3,433.0,20180611041451.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:14:51,2.828427,FLASH,...,1545.363,1.4911,1,1,1,1,NaN,2018-06-11 04:14:51,0,POINT (-153.60531313 11.25170837)
4,434.0,20180611041501.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:01,2.828427,FLASH,...,1545.324,1.4747,1,1,1,1,NaN,2018-06-11 04:15:01,0,POINT (-153.60531414 11.25170299)
5,435.0,20180611041511.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:11,2.828427,FLASH,...,1545.298,1.4635,1,1,1,1,NaN,2018-06-11 04:15:11,0,POINT (-153.60531664 11.25169768)
6,436.0,20180611041521.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:21,2.828427,FLASH,...,1545.315,1.4697,1,1,1,1,NaN,2018-06-11 04:15:21,0,POINT (-153.6053176 11.25169125)
7,437.0,20180611041531.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:31,2.828427,FLASH,...,1545.326,1.4727,1,1,1,1,NaN,2018-06-11 04:15:31,0,POINT (-153.60532046 11.25168357)
8,438.0,20180611041541.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:41,2.828427,FLASH,...,1545.266,1.4532,1,1,1,1,NaN,2018-06-11 04:15:41,0,POINT (-153.60532129 11.25167559)
9,439.0,20180611041551.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:15:51,2.828427,FLASH,...,1545.263,1.4512,1,1,1,1,NaN,2018-06-11 04:15:51,0,POINT (-153.60532147 11.25166737)
10,440.0,20180611041601.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:01,2.828427,FLASH,...,1545.248,1.4490,1,1,1,1,NaN,2018-06-11 04:16:01,0,POINT (-153.60532189 11.25165983)
11,441.0,20180611041611.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:11,2.828427,FLASH,...,1545.249,1.4485,1,1,1,1,NaN,2018-06-11 04:16:11,0,POINT (-153.60532254 11.25165416)
12,442.0,20180611041621.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:21,2.828427,FLASH,...,1545.232,1.4455,1,1,1,1,NaN,2018-06-11 04:16:21,0,POINT (-153.60532147 11.25164913)
13,443.0,20180611041631.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:31,2.828427,FLASH,...,1545.228,1.4456,1,1,1,1,NaN,2018-06-11 04:16:31,0,POINT (-153.60532064 11.2516466)
14,444.0,20180611041641.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:41,2.828427,FLASH,...,1545.241,1.4515,1,1,1,1,NaN,2018-06-11 04:16:41,0,POINT (-153.60532022 11.25164222)
15,445.0,20180611041651.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:16:51,2.828427,FLASH,...,1545.232,1.4506,1,1,1,1,NaN,2018-06-11 04:16:51,0,POINT (-153.60531968 11.25163773)
16,446.0,20180611041701.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:01,2.828427,FLASH,...,1545.237,1.4540,1,1,1,1,NaN,2018-06-11 04:17:01,0,POINT (-153.60532004 11.25163429)
17,447.0,20180611041711.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:11,2.828427,FLASH,...,1545.247,1.4593,1,1,1,1,NaN,2018-06-11 04:17:11,0,POINT (-153.60532082 11.25163155)
18,448.0,20180611041721.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:21,2.828427,FLASH,...,1545.228,1.4537,1,1,1,1,NaN,2018-06-11 04:17:21,0,POINT (-153.60532022 11.25162976)
19,449.0,20180611041731.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:31,2.828427,FLASH,...,1545.206,1.4478,1,1,1,1,NaN,2018-06-11 04:17:31,0,POINT (-153.60531831 11.25162916)
20,450.0,20180611041741.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:41,2.828427,FLASH,...,1545.206,1.4487,1,1,1,1,NaN,2018-06-11 04:17:41,0,POINT (-153.60531468 11.25162876)
21,451.0,20180611041751.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:17:51,2.828427,FLASH,...,1545.198,1.4473,1,1,1,1,NaN,2018-06-11 04:17:51,0,POINT (-153.60531062 11.25162821)
22,452.0,20180611041801.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:01,2.828427,FLASH,...,1545.190,1.4460,1,1,1,1,NaN,2018-06-11 04:18:01,0,POINT (-153.60530782 11.25162813)
23,453.0,20180611041811.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:11,2.828427,FLASH,...,1545.203,1.4546,1,1,1,1,NaN,2018-06-11 04:18:11,0,POINT (-153.60529894 11.25163219)
24,454.0,20180611041821.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:21,2.828427,FLASH,...,1545.205,1.4557,1,1,1,1,NaN,2018-06-11 04:18:21,0,POINT (-153.60529078 11.251633)
25,455.0,20180611041831.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:31,2.828427,FLASH,...,1545.222,1.4606,1,1,1,1,NaN,2018-06-11 04:18:31,0,POINT (-153.60528577 11.25163374)
26,456.0,20180611041841.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:41,2.828427,FLASH,...,1545.154,1.4391,1,1,1,1,NaN,2018-06-11 04:18:41,0,POINT (-153.60527719 11.25163777)
27,457.0,20180611041851.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:18:51,2.828427,FLASH,...,1545.169,1.4447,1,1,1,0,NaN,2018-06-11 04:18:51,0,POINT (-153.60527218 11.25163858)
28,458.0,20180611041901.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:01,2.828427,FLASH,...,1545.159,1.4435,1,1,1,1,NaN,2018-06-11 04:19:01,0,POINT (-153.60526246 11.25164123)
29,459.0,20180611041911.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:11,2.828427,FLASH,...,1545.252,1.4755,1,1,1,1,NaN,2018-06-11 04:19:11,0,POINT (-153.60525466 11.25164016)
30,460.0,20180611041921.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:21,2.828427,FLASH,...,1545.194,1.4549,1,1,1,1,NaN,2018-06-11 04:19:21,0,POINT (-153.60524786 11.25163778)
31,461.0,20180611041931.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:31,2.828427,FLASH,...,1545.182,1.4517,1,1,1,1,NaN,2018-06-11 04:19:31,0,POINT (-153.60524077 11.25163374)
32,462.0,20180611041941.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:41,2.828427,FLASH,...,1545.189,1.4538,1,1,1,1,NaN,2018-06-11 04:19:41,0,POINT (-153.60523183 11.25162942)
33,463.0,20180611041951.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:19:51,2.828427,FLASH,...,1545.155,1.4427,1,1,1,1,NaN,2018-06-11 04:19:51,0,POINT (-153.60522104 11.25162529)
34,464.0,20180611042001.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:01,2.828427,FLASH,...,1545.132,1.4345,1,1,1,1,NaN,2018-06-11 04:20:01,0,POINT (-153.60521204 11.25162354)
35,465.0,20180611042011.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:11,2.828427,FLASH,...,1545.125,1.4327,1,1,1,1,NaN,2018-06-11 04:20:11,0,POINT (-153.6052031 11.25162276)
36,466.0,20180611042021.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:21,2.828427,FLASH,...,1545.124,1.4325,1,1,1,1,NaN,2018-06-11 04:20:21,0,POINT (-153.60519493 11.25162345)
37,467.0,20180611042031.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:31,2.828427,FLASH,...,1545.121,1.4321,1,1,1,1,NaN,2018-06-11 04:20:31,0,POINT (-153.60518772 11.25162512)
38,468.0,20180611042041.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:41,2.828427,FLASH,...,1545.116,1.4319,1,1,1,1,NaN,2018-06-11 04:20:41,0,POINT (-153.60518069 11.2516276)
39,469.0,20180611042051.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:20:51,2.828427,FLASH,...,1545.114,1.4314,1,1,1,1,NaN,2018-06-11 04:20:51,0,POINT (-153.60517508 11.2516303)
40,470.0,20180611042101.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:01,2.828427,FLASH,...,1545.111,1.4318,1,1,1,1,NaN,2018-06-11 04:21:01,0,POINT (-153.60516984 11.25163181)
41,471.0,20180611042111.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:11,2.828427,FLASH,...,1545.107,1.4315,1,1,1,1,NaN,2018-06-11 04:21:11,0,POINT (-153.60516435 11.2516341)
42,472.0,20180611042121.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:21,2.828427,FLASH,...,1545.111,1.4350,1,1,1,1,NaN,2018-06-11 04:21:21,0,POINT (-153.6051516 11.25164437)
43,473.0,20180611042131.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:31,2.828427,FLASH,...,1545.106,1.4378,1,1,1,1,NaN,2018-06-11 04:21:31,0,POINT (-153.60514236 11.25164693)
44,474.0,20180611042141.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:41,2.828427,FLASH,...,1545.109,1.4385,1,1,1,1,NaN,2018-06-11 04:21:41,0,POINT (-153.60513384 11.25165041)
45,475.0,20180611042151.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:21:51,2.828427,FLASH,...,1545.102,1.4329,1,1,1,1,NaN,2018-06-11 04:21:51,0,POINT (-153.60512829 11.25165104)
46,476.0,20180611042201.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:01,2.828427,FLASH,...,1545.102,1.4327,1,1,1,1,NaN,2018-06-11 04:22:01,0,POINT (-153.60512269 11.25165186)
47,477.0,20180611042211.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:11,2.828427,FLASH,...,1545.097,1.4326,1,1,1,1,NaN,2018-06-11 04:22:11,0,POINT (-153.60511554 11.25165272)
48,478.0,20180611042221.png,300.0,300.0,0.016667,8.0,200.0,2018-06-11 04:22:21,2.828427,FLASH,...,1545.115,1.4382,1,1,1,1,NaN,2018-06-11 04:22:21,0,POINT (-153.60511047 11.25165643)

### Option 3: using Configuration class and MetadataParser class

#### Using configuration parsing

In [10]:
config = Configuration(config_file_path="../config_files/config_simple.yml")
config

{
    "general": {
        "name": "raw",
        "step_name": "open",
        "sample_data": "benthic_csv",
        "input_path": "/home/tobfer/.paidiverpy_cache/benthic_csv/images",
        "output_path": "output",
        "metadata_path": "/home/tobfer/.paidiverpy_cache/benthic_csv/metadata/metadata_benthic_csv.csv",
        "metadata_type": "CSV_FILE",
        "image_open_args": "PNG",
        "append_data_to_metadata": "/home/tobfer/.paidiverpy_cache/benthic_csv/metadata/appended_metadata_benthic_csv.csv",
        "n_jobs": 1,
        "track_changes": true,
        "rename": "datetime",
        "sampling": [
            {
                "name": "sampling",
                "step_name": "sampling",
                "test": false,
                "params": {
                    "value": 0.1,
                    "raise_error": false
                },
                "mode": "percent"
            }
        ],
        "convert": [
            {
                "name": "convert",
                "step_name": "convert",
                "test": false,
                "params": {
                    "output_bits": 8,
                    "raise_error": false
                },
                "mode": "bits"
            },
            {
                "name": "convert",
                "step_name": "convert",
                "test": false,
                "params": {
                    "to": "gray",
                    "channel_selector": 0,
                    "raise_error": false
                },
                "mode": "to"
            }
        ]
    },
    "steps": []
}


In this case, you will not have access to the metadata, as it was not parsed yet

#### Parse only the metadata

In [11]:
# You need to pass the configuration file
metadata = MetadataParser(config=config)
metadata

<xarray.DataArray (filename: 49)> Size: 392B
array([{'ID': 430.0, 'filename': '20180611041421.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:14:21'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 426737, 'image-longitude': -153.60531587, 'image-latitude': 11.25172554, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.937, 'image-camera-pitch-degrees': 2.287, 'heading_deg': 90.751, 'cog_deg': 188.426969021481, 'image-depth': 5203.744, 'sog_m_s': 0.0272946881279124, 'time_unix_seconds': 1528690461.02041, 'conductivity': 3.21279, 'depth_m.1': 5203.744, 'pressure_psi': 7688.29530138297, 'salinity': 34.6773, 'speed_of_sound_m_s': 1545.388, 'temperature_c': 1.5059, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:14:21', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 431.0, 'filename': '20180611041431.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:14:31'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 426916, 'image-longitude': -153.60531372, 'image-latitude': 11.25171832, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 1.326, 'image-camera-pitch-degrees': 1.993, 'heading_deg': 89.866, 'cog_deg': 221.63353933657, 'image-depth': 5203.744, 'sog_m_s': 0.0240831891575846, 'time_unix_seconds': 1528690471.02991, 'conductivity': 3.21329, 'depth_m.1': 5203.744, 'pressure_psi': 7688.29530138297, 'salinity': 34.6647, 'speed_of_sound_m_s': 1545.447, 'temperature_c': 1.5236, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:14:31', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 432.0, 'filename': '20180611041441.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:14:41'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 427094, 'image-longitude': -153.60531259, 'image-latitude': 11.2517135, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.577, 'image-camera-pitch-degrees': 1.59, 'heading_deg': 90.486, 'cog_deg': 226.847610265995, 'image-depth': 5203.785, 'sog_m_s': 0.0219317121994613, 'time_unix_seconds': 1528690481.01456, 'conductivity': 3.21359, 'depth_m.1': 5203.785, 'pressure_psi': 7688.35766761031, 'salinity': 34.6686, 'speed_of_sound_m_s': 1545.452, 'temperature_c': 1.5234, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:14:41', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 433.0, 'filename': '20180611041451.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:14:51'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 427274, 'image-longitude': -153.60531313, 'image-latitude': 11.25170837, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.841, 'image-camera-pitch-degrees': 2.262, 'heading_deg': 90.468, 'cog_deg': 232.125016348902, 'image-depth': 5203.724, 'sog_m_s': 0.0114017542509914, 'time_unix_seconds': 1528690491.06994, 'conductivity': 3.21395, 'depth_m.1': 5203.724, 'pressure_psi': 7688.26484345799, 'salinity': 34.7067, 'speed_of_sound_m_s': 1545.363, 'temperature_c': 1.4911, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:14:51', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 434.0, 'filename': '20180611041501.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:15:01'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 427452, 'image-longitude': -153.60531414, 'image-latitude': 11.25170299, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 1.01, 'image-camera-pitch-degrees': 1.545, 'heading_deg': 89.988, 'cog_deg': 245.772254682046, 'image-depth': 5203.703, 'sog_m_s': 0.0219317121994613, 'time_unix_seconds': 1528690501.01889, 'conductivity': 3.21446, 'depth_m.1': 5203.703, 'pressure_psi': 7688.234385533, 'salinity': 34.7302, 'speed_of_sound_m_s': 1545.324, 'temperature_c': 1.4747, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:15:01', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 435.0, 'filename': '20180611041511.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:15:11'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 427630, 'image-longitude': -153.60531664, 'image-latitude': 11.25169768, 'image-altitude-meters': 1.6, 'image-camera-roll-degrees': 0.503, 'image-camera-pitch-degrees': 1.394, 'heading_deg': 90.419, 'cog_deg': 228.012787504183, 'image-depth': 5203.653, 'sog_m_s': 0.0134536240470737, 'time_unix_seconds': 1528690511.01836, 'conductivity': 3.2149, 'depth_m.1': 5203.653, 'pressure_psi': 7688.15896590924, 'salinity': 34.7474, 'speed_of_sound_m_s': 1545.298, 'temperature_c': 1.4635, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:15:11', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 436.0, 'filename': '20180611041521.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:15:21'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 427808, 'image-longitude': -153.6053176, 'image-latitude': 11.25169125, 'image-altitude-meters': 1.6, 'image-camera-roll-degrees': 0.725, 'image-camera-pitch-degrees': 2.818, 'heading_deg': 90.627, 'cog_deg': 270.0, 'image-depth': 5203.653, 'sog_m_s': 0.014, 'time_unix_seconds': 1528690521.00569, 'conductivity': 3.21489, 'depth_m.1': 5203.653, 'pressure_psi': 7688.15896590924, 'salinity': 34.7407, 'speed_of_sound_m_s': 1545.315, 'temperature_c': 1.4697, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:15:21', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 437.0, 'filename': '20180611041531.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:15:31'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 427988, 'image-longitude': -153.60532046, 'image-latitude': 11.25168357, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.7, 'image-camera-pitch-degrees': 3.255, 'heading_deg': 89.979, 'cog_deg': 265.914383220025, 'image-depth': 5203.806, 'sog_m_s': 0.0140356688476182, 'time_unix_seconds': 1528690531.0678, 'conductivity': 3.21483, 'depth_m.1': 5203.806, 'pressure_psi': 7688.38667515791, 'salinity': 34.7368, 'speed_of_sound_m_s': 1545.326, 'temperature_c': 1.4727, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:15:31', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 438.0, 'filename': '20180611041541.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:15:41'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 428166, 'image-longitude': -153.60532129, 'image-latitude': 11.25167559, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.845, 'image-camera-pitch-degrees': 1.886, 'heading_deg': 90.377, 'cog_deg': 259.380344723845, 'image-depth': 5203.724, 'sog_m_s': 0.0162788205960997, 'time_unix_seconds': 1528690541.05393, 'conductivity': 3.21469, 'depth_m.1': 5203.724, 'pressure_psi': 7688.26484345799, 'salinity': 34.7556, 'speed_of_sound_m_s': 1545.266, 'temperature_c': 1.4532, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:15:41', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 439.0, 'filename': '20180611041551.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:15:51'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 428344, 'image-longitude': -153.60532147, 'image-latitude': 11.25166737, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.731, 'image-camera-pitch-degrees': 2.273, 'heading_deg': 90.602, 'cog_deg': 298.072486935853, 'image-depth': 5203.756, 'sog_m_s': 0.017, 'time_unix_seconds': 1528690551.05698, 'conductivity': 3.21481, 'depth_m.1': 5203.756, 'pressure_psi': 7688.31270591153, 'salinity': 34.759, 'speed_of_sound_m_s': 1545.263, 'temperature_c': 1.4512, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:15:51', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 440.0, 'filename': '20180611041601.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:16:01'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 428522, 'image-longitude': -153.60532189, 'image-latitude': 11.25165983, 'image-altitude-meters': 1.6, 'image-camera-roll-degrees': 0.837, 'image-camera-pitch-degrees': 1.101, 'heading_deg': 90.093, 'cog_deg': 294.775140568832, 'image-depth': 5203.694, 'sog_m_s': 0.0143178210632764, 'time_unix_seconds': 1528690561.01589, 'conductivity': 3.21441, 'depth_m.1': 5203.694, 'pressure_psi': 7688.22133213658, 'salinity': 34.7566, 'speed_of_sound_m_s': 1545.248, 'temperature_c': 1.449, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:16:01', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 441.0, 'filename': '20180611041611.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:16:11'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 428700, 'image-longitude': -153.60532254, 'image-latitude': 11.25165416, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.966, 'image-camera-pitch-degrees': 1.406, 'heading_deg': 90.64, 'cog_deg': 310.236358309274, 'image-depth': 5203.817, 'sog_m_s': 0.0170293863659264, 'time_unix_seconds': 1528690571.00514, 'conductivity': 3.21436, 'depth_m.1': 5203.817, 'pressure_psi': 7688.40407968647, 'salinity': 34.7564, 'speed_of_sound_m_s': 1545.249, 'temperature_c': 1.4485, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:16:11', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 442.0, 'filename': '20180611041621.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:16:21'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 428879, 'image-longitude': -153.60532147, 'image-latitude': 11.25164913, 'image-altitude-meters': 1.6, 'image-camera-roll-degrees': 0.432, 'image-camera-pitch-degrees': 1.34, 'heading_deg': 90.433, 'cog_deg': 335.556045219583, 'image-depth': 5203.703, 'sog_m_s': 0.0120830459735946, 'time_unix_seconds': 1528690581.04368, 'conductivity': 3.21398, 'depth_m.1': 5203.703, 'pressure_psi': 7688.234385533, 'salinity': 34.755, 'speed_of_sound_m_s': 1545.232, 'temperature_c': 1.4455, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:16:21', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 443.0, 'filename': '20180611041631.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:16:31'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 429057, 'image-longitude': -153.60532064, 'image-latitude': 11.2516466, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.701, 'image-camera-pitch-degrees': 2.646, 'heading_deg': 90.561, 'cog_deg': 2.12109639666145, 'image-depth': 5203.735, 'sog_m_s': 0.0270185121722126, 'time_unix_seconds': 1528690591.02032, 'conductivity': 3.21372, 'depth_m.1': 5203.735, 'pressure_psi': 7688.28224798655, 'salinity': 34.7518, 'speed_of_sound_m_s': 1545.228, 'temperature_c': 1.4456, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:16:31', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 444.0, 'filename': '20180611041641.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:16:41'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 429235, 'image-longitude': -153.60532022, 'image-latitude': 11.25164222, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.705, 'image-camera-pitch-degrees': 3.037, 'heading_deg': 90.376, 'cog_deg': 353.418055344822, 'image-depth': 5203.766, 'sog_m_s': 0.0261725046566048, 'time_unix_seconds': 1528690601.0077, 'conductivity': 3.2134, 'depth_m.1': 5203.766, 'pressure_psi': 7688.32720968533, 'salinity': 34.7417, 'speed_of_sound_m_s': 1545.241, 'temperature_c': 1.4515, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:16:41', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 445.0, 'filename': '20180611041651.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:16:51'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 429415, 'image-longitude': -153.60531968, 'image-latitude': 11.25163773, 'image-altitude-meters': 1.6, 'image-camera-roll-degrees': 1.092, 'image-camera-pitch-degrees': 2.186, 'heading_deg': 90.058, 'cog_deg': 337.750976342788, 'image-depth': 5203.724, 'sog_m_s': 0.0237697286480094, 'time_unix_seconds': 1528690611.06968, 'conductivity': 3.21309, 'depth_m.1': 5203.724, 'pressure_psi': 7688.26484345799, 'salinity': 34.739, 'speed_of_sound_m_s': 1545.232, 'temperature_c': 1.4506, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:16:51', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 446.0, 'filename': '20180611041701.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:17:01'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 429593, 'image-longitude': -153.60532004, 'image-latitude': 11.25163429, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.536, 'image-camera-pitch-degrees': 1.977, 'heading_deg': 90.765, 'cog_deg': 338.198590513648, 'image-depth': 5203.777, 'sog_m_s': 0.0269258240356725, 'time_unix_seconds': 1528690621.00762, 'conductivity': 3.21271, 'depth_m.1': 5203.777, 'pressure_psi': 7688.34316383651, 'salinity': 34.7307, 'speed_of_sound_m_s': 1545.237, 'temperature_c': 1.454, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:17:01', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 447.0, 'filename': '20180611041711.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:17:11'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 429771, 'image-longitude': -153.60532082, 'image-latitude': 11.25163155, 'image-altitude-meters': 1.6, 'image-camera-roll-degrees': 0.904, 'image-camera-pitch-degrees': 0.347, 'heading_deg': 90.316, 'cog_deg': 356.531770741083, 'image-depth': 5203.715, 'sog_m_s': 0.0330605505096331, 'time_unix_seconds': 1528690631.02903, 'conductivity': 3.21248, 'depth_m.1': 5203.715, 'pressure_psi': 7688.25179006156, 'salinity': 34.7223, 'speed_of_sound_m_s': 1545.247, 'temperature_c': 1.4593, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:17:11', 'flag': 0, 'point': <POINT (-153.605 11.252)>},
       {'ID': 448.0, 'filename': '20180611041721.png', 'XResolution': 300.0, 'YResolution': 300.0, 'ExposureTime': 0.01666666667, 'FNumber': 8.0, 'ISO': 200.0, 'image-datetime': Timestamp('2018-06-11 04:17:21'), 'MaxApertureValue': 2.82842712474619, 'WhiteBalance': 'FLASH       ', 'FocusPosition': 17.0, 'FocusDistance': 0.298538261891796, 'Unnamed: 0': 429949, 'image-longitude': -153.60532022, 'image-latitude': 11.25162976, 'image-altitude-meters': 1.5, 'image-camera-roll-degrees': 0.933, 'image-camera-pitch-degrees': 1.649, 'heading_deg': 90.269, 'cog_deg': 25.1148348861446, 'image-depth': 5203.756, 'sog_m_s': 0.0353411940941446, 'time_unix_seconds': 1528690641.01444, 'conductivity': 3.21221, 'depth_m.1': 5203.756, 'pressure_psi': 7688.31270591153, 'salinity': 34.725, 'speed_of_sound_m_s': 1545.228, 'temperature_c': 1.4537, 'positioning_ok': 1, 'attitude_ok': 1, 'depth_ok': 1, 'altitude_ok': 1, 'X': nan, 'phototime': '2018-06-11 04:17:21', 'flag': 0, 'point': <POINT (-153.605 11.252)>},